### ISSUE TITLE
[BUG] Cannot use leantime (blank screen) due to SQL error

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1608]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
I updated to the latest code in the repository using `git pull` and rebuilding the `js` files using Grunt. When accessing the site and successfully logging in, after a database update, the screen is blank. The error log contains the error message below.

**To Reproduce**
1. Update to the latest version
2. Log in
3. Screen is blank
4. See error in log file

```
[30-Apr-2023 15:29:35 Europe/Zurich] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'moduleId' in 'field list' in /opt/leantime23b/app/domain/reactions/repositories/class.reactions.php:136
Stack trace:
#0 /opt/leantime23b/app/domain/reactions/repositories/class.reactions.php(136): PDOStatement->execute()
#1 /opt/leantime23b/app/domain/reactions/services/class.reactions.php(103): leantime\domain\repositories\reactions->getUserReactions()
#2 /opt/leantime23b/app/domain/dashboard/controllers/class.show.php(56): leantime\domain\services\reactions->getUserReactions()
#3 /opt/leantime23b/app/core/class.controller.php(61): leantime\domain\controllers\show->get()
#4 /opt/leantime23b/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#5 /opt/leantime23b/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#6 /opt/leantime23b/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction()
#7 /opt/leantime23b/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch()
#8 /opt/leantime23b/public/index.php(26): leantime\core\application->start()
#9 {main}
```

**Leantime Version**
2.3.20 / 2.1.16

**Server**
Apache

**PHP / MySQL Version**
8.1

**Additional context**
None

**Comment by marcelfolaron** [comment]
Hey,
There was a mistake in the install/update sql script. The column name should have been `moduleId` instead of `entityId`.
I updated the installer and udpate script but you may have to run the query manually:

```sql
ALTER TABLE `zp_reactions` 
CHANGE COLUMN `entityId` `moduleId` INT(11) NULL DEFAULT NULL ;
```

**Comment by marcelfolaron** [comment]
Alternatively you could remove the table and reset db version in the settings table to rerun the updater.

**Comment by marcelfolaron** [comment]
PPS: I also still need to do some updates to the full menu. The icons and tooltips have not been created yet.

**Comment by diderich** [comment]
Altered the table. Now I get to the menu (see below) and receive the following error:;

```
[30-Apr-2023 16:16:15 Europe/Zurich] PHP Warning:  Undefined array key "tooltip" in /opt/leantime23b/app/domain/menu/templates/menu.tpl.php on line 131
[30-Apr-2023 16:16:15 Europe/Zurich] PHP Fatal error:  Uncaught TypeError: leantime\core\language::__(): Argument #1 ($index) must be of type string, null given, called in /opt/leantime23b/app/core/class.template.php on line 467 and defined in /opt/leantime23b/app/core/class.language.php:392
Stack trace:
#0 /opt/leantime23b/app/core/class.template.php(467): leantime\core\language->__()
#1 /opt/leantime23b/app/domain/menu/templates/menu.tpl.php(131): leantime\core\template->__()
#2 /opt/leantime23b/app/core/class.template.php(251): require_once('...')
#3 /opt/leantime23b/app/core/class.template.php(299): leantime\core\template->display()
#4 /opt/leantime23b/app/domain/menu/controllers/class.menu.php(84): leantime\core\template->displayPartial()
#5 /opt/leantime23b/app/core/class.controller.php(63): leantime\domain\controllers\menu->run()
#6 /opt/leantime23b/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#7 /opt/leantime23b/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#8 /opt/leantime23b/app/core/class.frontcontroller.php(237): leantime\core\frontcontroller::executeAction()
#9 /opt/leantime23b/public/theme/default/layout/app.php(23): leantime\core\frontcontroller::includeAction()
#10 /opt/leantime23b/app/core/class.template.php(232): require('...')
#11 /opt/leantime23b/app/domain/dashboard/controllers/class.show.php(97): leantime\core\template->display()
#12 /opt/leantime23b/app/core/class.controller.php(61): leantime\domain\controllers\show->get()
#13 /opt/leantime23b/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#14 /opt/leantime23b/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#15 /opt/leantime23b/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction()
#16 /opt/leantime23b/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch()
#17 /opt/leantime23b/public/index.php(26): leantime\core\application->start()
#18 {main}
  thrown in /opt/leantime23b/app/core/class.language.php on line 392
```

![Screenshot 2023-04-30 161823](https://user-images.githubusercontent.com/10230144/235358024-79c70316-9f22-487d-994b-82d1722713a9.jpg)

**Comment by diderich** [comment]
Re-pulled the latest changes. Now it's working again :-)
