### ISSUE TITLE
[BUG] Can't skip wizard at first login and can't create the first project

### ISSUE THREAD

**Issue by tech62** [Leantime/leantime#1760]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X ] Self Hosted

**Describe the bug**
After the first login, a wizard start and ask a name of the first project, i can't skip this wizard and if i give a name for the project an exception happenned

**To Reproduce**
1. Fresh install
2. Create .env and configure AD and SMTP and role
3. Login into leantime
4. Click to skip (no effect) or give a name to the first project

**Expected behavior**
No exception on the first user login.

**Leantime Version**
v2.3.26

**Server**
Nginx

**PHP / MySQL Version**
php8.2-fpm
Server version: 10.11.3-MariaDB-1 Debian 12
![leantime_bug](https://github.com/Leantime/leantime/assets/16237642/2602349a-732f-416b-bf38-2e5af0cb0c03)

### Error.log
```
[22-Jul-2023 10:21:55 Europe/Paris] PHP Deprecated:  Creation of dynamic property leantime\plugins\services\motivationalQuotes::$quotesRepo is deprecated in /var/www/leantime/app/plugins/motivationalQuotes/services/class.motivationalQuotes.php on line 11
[22-Jul-2023 10:21:56 Europe/Paris] PHP Warning:  Undefined array key "currentProjectName" in /var/www/leantime/app/domain/help/templates/firstLoginDialog.tpl.php on line 110
[22-Jul-2023 10:21:59 Europe/Paris] PHP Fatal error:  Uncaught TypeError: leantime\domain\services\projects::isUserAssignedToProject(): Argument #2 ($projectId) must be of type int, string given, called in /var/www/leantime/app/domain/projects/services/class.projects.php on line 421 and defined in /var/www/leantime/app/domain/projects/services/class.projects.php:549
Stack trace:
#0 /var/www/leantime/app/domain/projects/services/class.projects.php(421): leantime\domain\services\projects->isUserAssignedToProject()
#1 /var/www/leantime/app/domain/help/controllers/class.firstLogin.php(48): leantime\domain\services\projects->changeCurrentSessionProject()
#2 /var/www/leantime/app/core/class.controller.php(61): leantime\domain\controllers\firstLogin->post()
#3 /var/www/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions()
#4 /var/www/leantime/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct()
#5 /var/www/leantime/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction()
#6 /var/www/leantime/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch()
#7 /var/www/leantime/public/index.php(26): leantime\core\application->start()
#8 {main}
  thrown in /var/www/leantime/app/domain/projects/services/class.projects.php on line 549
```

### Error shown on browser 
```
Fatal error: Uncaught TypeError: leantime\domain\services\projects::isUserAssignedToProject(): Argument #2 ($projectId) must be of type int, string given, called in /var/www/leantime/app/domain/projects/services/class.projects.php on line 421 and defined in /var/www/leantime/app/domain/projects/services/class.projects.php:549 Stack trace: #0 /var/www/leantime/app/domain/projects/services/class.projects.php(421): leantime\domain\services\projects->isUserAssignedToProject() #1 /var/www/leantime/app/domain/help/controllers/class.firstLogin.php(48): leantime\domain\services\projects->changeCurrentSessionProject() #2 /var/www/leantime/app/core/class.controller.php(61): leantime\domain\controllers\firstLogin->post() #3 /var/www/leantime/app/core/class.controller.php(33): leantime\core\controller->executeActions() #4 /var/www/leantime/app/core/class.frontcontroller.php(176): leantime\core\controller->__construct() #5 /var/www/leantime/app/core/class.frontcontroller.php(98): leantime\core\frontcontroller::executeAction() #6 /var/www/leantime/app/core/class.application.php(127): leantime\core\frontcontroller::dispatch() #7 /var/www/leantime/public/index.php(26): leantime\core\application->start() #8 {main} thrown in /var/www/leantime/app/domain/projects/services/class.projects.php on line 549
```
### When i execute the query 
```
insert into zp_settings VALUES ("companysettings.completedOnboarding", true);
```
The Wizard disappear and i'm able to use leantime

**Comment by marcelfolaron** [comment]
Issue fixed in 2.3.27
