### ISSUE TITLE
[BUG] Uncaught ReflectionException: Class "leantime\\domain\\services\\modulemanager" does not exist

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1783]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
After downloading the latest version with `git pull`, I receive the following error message in my log file:
```
[Mon Jul 31 15:42:24.413527 2023] [php:error] [pid 4462] [client 172.16.1.40:59955] PHP Fatal error:  Uncaught ReflectionException: Class "leantime\\domain\\services\\modulemanager" does not exist in /opt/leantime23b/vendor/illuminate/container/Container.php:877
Stack trace:
#0 /opt/leantime23b/vendor/illuminate/container/Container.php(877): ReflectionClass->__construct()
#1 /opt/leantime23b/vendor/illuminate/container/Container.php(758): Illuminate\\Container\\Container->build()
#2 /opt/leantime23b/vendor/illuminate/container/Container.php(694): Illuminate\\Container\\Container->resolve()
#3 /opt/leantime23b/app/core/class.Bootloader.php(172): Illuminate\\Container\\Container->make()
#4 /opt/leantime23b/app/core/class.Bootloader.php(101): leantime\\core\\Bootloader->getApplication()
#5 /opt/leantime23b/public/index.php(11): leantime\\core\\Bootloader->boot()
#6 {main}

Next Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [leantime\\domain\\services\\modulemanager] does not exist. in /opt/leantime23b/vendor/illuminate/container/Container.php:879
Stack trace:
#0 /opt/leantime23b/vendor/illuminate/container/Container.php(758): Illuminate\\Container\\Container->build()
#1 /opt/leantime23b/vendor/illuminate/container/Container.php(694): Illuminate\\Container\\Container->resolve()
#2 /opt/leantime23b/app/core/class.Bootloader.php(172): Illuminate\\Container\\Container->make()
#3 /opt/leantime23b/app/core/class.Bootloader.php(101): leantime\\core\\Bootloader->getApplication()
#4 /opt/leantime23b/public/index.php(11): leantime\\core\\Bootloader->boot()
#5 {main}
  thrown in /opt/leantime23b/vendor/illuminate/container/Container.php on line 879
```

![mm](https://github.com/Leantime/leantime/assets/10230144/d98d53c7-1ee3-4f7a-b59e-c97a790383fe)

**Leantime Version**
Which Leantime version are you using: 2.3.27 / 2.1.21 (db)

**Server**
Apache

**PHP / MySQL Version**
8.1.21

**Comment by carlos-ortega-talentum** [comment]
same here

**Comment by marcelfolaron** [comment]
Can you
