### ISSUE TITLE
[BUG] Logged in - but "An error occured" blocking ability to use Leantime

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#1851]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X ] Self Hosted

**Describe the bug**
Immediately upon logging in I get an error message that I cannot get past:
![image](https://github.com/Leantime/leantime/assets/121611/0862aa33-3d8f-429f-86f6-f72b1e344c20)

**To Reproduce**
1. Fresh / New Installation (LDAP in my case)
2. Login
3. Presents white box "An error has occurred"
![image](https://github.com/Leantime/leantime/assets/121611/ae1894fa-db75-460b-88e0-e9b59e800f2b)
4. Closing the box immediately respawns the same error dialog box.  Can't get past it.

**Expected behavior**
To begin using the software ;-)

**Leantime Version**
2.4-beta

**Server**
NGINX

**PHP / MySQL Version**
8.1 / Mariadb 10.3

**Additional context**
This video demonstrates the issue:
* https://www.youtube.com/watch?v=L2-HS6VFSrA
error.log results that coincide with error dialog window:
```
[27-Aug-2023 14:47:20 America/Los_Angeles] ErrorException: Warning: Undefined array key "currentProjectName" in /SM_DATA/web_projects/public_html/app/domain/help/templates/firstLoginDialog.tpl.php:112
Stack trace:
#0 /SM_DATA/web_projects/public_html/vendor/illuminate/filesystem/Filesystem.php(109): require('...')
#1 /SM_DATA/web_projects/public_html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /SM_DATA/web_projects/public_html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#3 /SM_DATA/web_projects/public_html/vendor/illuminate/view/Engines/PhpEngine.php(38): Illuminate\View\Engines\PhpEngine->evaluatePath()
#4 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\PhpEngine->get()
#5 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#6 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#7 /SM_DATA/web_projects/public_html/cache/views/d2d7f392fdd66567dc4e036cf3464d7247dbd85f.php(2): Illuminate\View\View->render()
#8 /SM_DATA/web_projects/public_html/vendor/illuminate/filesystem/Filesystem.php(109): require('...')
#9 /SM_DATA/web_projects/public_html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#10 /SM_DATA/web_projects/public_html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#11 /SM_DATA/web_projects/public_html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath()
#12 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#13 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#14 /SM_DATA/web_projects/public_html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#15 /SM_DATA/web_projects/public_html/app/core/class.template.php(444): Illuminate\View\View->render()
#16 /SM_DATA/web_projects/public_html/app/core/class.template.php(488): leantime\core\template->display()
#17 /SM_DATA/web_projects/public_html/app/domain/help/controllers/class.firstLogin.php(32): leantime\core\template->displayPartial()
#18 /SM_DATA/web_projects/public_html/app/core/class.controller.php(91): leantime\domain\controllers\firstLogin->get()
#19 /SM_DATA/web_projects/public_html/app/core/class.controller.php(53): leantime\core\controller->executeActions()
#20 [internal function]: leantime\core\controller->__construct()
#21 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#22 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#23 /SM_DATA/web_projects/public_html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#24 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(151): Illuminate\Container\Container->make()
#25 /SM_DATA/web_projects/public_html/app/core/class.frontcontroller.php(73): leantime\core\frontcontroller::executeAction()
#26 /SM_DATA/web_projects/public_html/app/core/class.Bootloader.php(378): leantime\core\frontcontroller::dispatch()
#27 /SM_DATA/web_projects/public_html/app/core/class.Bootloader.php(154): leantime\core\Bootloader->handleRequest()
#28 /SM_DATA/web_projects/public_html/public/index.php(11): leantime\core\Bootloader->boot()
#29 {main}
```

**Comment by marcelfolaron** [comment]
Fixed in 2.4-beta-4
