### ISSUE TITLE
[BUG] file upload not working / images not shown

### ISSUE THREAD

**Issue by schories** [Leantime/leantime#1934]
**What set up are you using**
* [X] Self Hosted - [2.4-beta-6](https://hub.docker.com/layers/leantime/leantime/2.4-beta-6/images/sha256-e2e6549ee5ce994574cc32d6741ebb880d4bd704646d19ef849b2a2b05bbfd34?context=explore)

**Describe the bug**
Uploading a profile photo or files causes no visual error, but no profile picture or files are shown afterwards. Instead the "missing picture / broken link" icon is shown by the webbrowser.

**To Reproduce**
1. Go to profile
2. upload photo - preview for sizing/cutting the photo is showing the photo
3. Click on save: no error, but no profile photo is shown

**Expected behavior**
Uploaded content should be visible/shown.

**Leantime Version**
[2.4-beta-6](https://hub.docker.com/layers/leantime/leantime/2.4-beta-6/images/sha256-e2e6549ee5ce994574cc32d6741ebb880d4bd704646d19ef849b2a2b05bbfd34?context=explore)

**Errors in Docker Container Logs**
[29-Sep-2023 13:14:06 Europe/Paris] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/app/Domain/Users/Repositories/Users.php on line 671
[29-Sep-2023 13:14:06 Europe/Paris] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/app/Domain/Users/Repositories/Users.php on line 672
[29-Sep-2023 13:14:06 Europe/Paris] PHP Warning:  Undefined variable $return in /var/www/html/app/Domain/Users/Repositories/Users.php on line 674
[29-Sep-2023 13:14:06 Europe/Paris] PHP Warning:  Undefined array key "extension" in /var/www/html/app/Core/Fileupload.php on line 393

I don't know whether up/downgrading docker images caused the issue - maybe in the database?

Docker volumes are set up as they have been before, means for userfiles.
However, no files show up after uploading in the actual volume directories. So it seems they never make it to disk.

**Comment by marcelfolaron** [comment]
Interesting. What type of image are you trying to upload? The line in which it is failing says that it cannot find the file extension. So it doesn't know what type of file it is. The data comes from pathinfo(). Based on that it would only fail if the extension is actually missing: https://www.php.net/manual/en/function.pathinfo.php

**Comment by schories** [comment]
I tried with PNG. Also tried JPG. 512üx x 512px. Also larger. Preview works. But after saving, it's gone. So strange..

**Comment by marcelfolaron** [comment]
Strange indeed. I will do some additional testing.

**Comment by schories** [comment]
I updated docker compose config just now

from:     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
to:        command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci

And now found also in the error:log: 

[29-Sep-2023 16:59:52 Europe/Paris] PHP Warning:  move_uploaded_file(/var/www/html/userfiles/a75bf1206323a40dbd344fb9049be83d.png): Failed to open stream: Permission denied in /var/www/html/app/Core/Fileupload.php on line 323
[29-Sep-2023 16:59:52 Europe/Paris] PHP Warning:  move_uploaded_file(): Unable to move &quot;/tmp/phpLidOMj&quot; to &quot;/var/www/html/userfiles/a75bf1206323a40dbd344fb9049be83d.png&quot; in /var/www/html/app/Core/Fileupload.php on line 323

So somehow I do have a permission problem. Hmm...

**Comment by schories** [comment]
I have to thank you.! :)

**Comment by schories** [comment]
I apologize for re-opening this, as with 2.4 (https://hub.docker.com/layers/leantime/leantime/2.4/images/sha256-ae3f454c99c6f5d92f192b7a03d2055581bbacd8dadaa649a3001b8b9dc10b1b?context=explore) the issue is still present:

- now the "save" circling animation is running indefinitely
- and the following entries show up in the error log.

#0 /var/www/html/app/Domain/Api/Controllers/Users.php(64): Leantime\Core\Fileupload->displayImageFile(NULL)
#1 /var/www/html/app/Core/Controller.php(98): Leantime\Domain\Api\Controllers\Users->get(Array)
#2 /var/www/html/app/Core/Controller.php(59): Leantime\Core\Controller->executeActions('GET', Array)
#3 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#4 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#5 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#6 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#7 /var/www/html/app/Core/Frontcontroller.php(120): Illuminate\Container\Container->make('Leantime\\Domain...')
#8 /var/www/html/app/Core/Frontcontroller.php(74): Leantime\Core\Frontcontroller::executeAction('api.users', Array)
#9 /var/www/html/app/Core/Bootloader.php(419): Leantime\Core\Frontcontroller::dispatch()
#10 /var/www/html/app/Core/Bootloader.php(165): Leantime\Core\Bootloader->handleRequest()
#11 /var/www/html/public/index.php(14): Leantime\Core\Bootloader->boot()
#12 {main}
  thrown in /var/www/html/app/Core/Fileupload.php on line 358
[08-Oct-2023 10:43:50 Europe/Paris] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/app/Domain/Users/Repositories/Users.php on line 650
[08-Oct-2023 10:43:50 Europe/Paris] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/app/Domain/Users/Repositories/Users.php on line 650
[08-Oct-2023 10:43:50 Europe/Paris] PHP Warning:  move_uploaded_file(/var/www/html/userfiles/7c4993fc0939b58b60cd4ab91c791c94.png): Failed to open stream: Permission denied in /var/www/html/app/Core/Fileupload.php on line 340
[08-Oct-2023 10:43:50 Europe/Paris] PHP Warning:  move_uploaded_file(): Unable to move &quot;/tmp/phppfBBDd&quot; to &quot;/var/www/html/userfiles/7c4993fc0939b58b60cd4ab91c791c94.png&quot; in /var/www/html/app/Core/Fileupload.php on line 340
[08-Oct-2023 10:43:50 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Leantime\Domain\Files\Repositories\Files::upload(): Return value must be of type array|false, string returned in /var/www/html/app/Domain/Files/Repositories/Files.php:306
Stack trace:
#0 /var/www/html/app/Domain/Users/Repositories/Users.php(656): Leantime\Domain\Files\Repositories\Files->upload(Array, 'user', 1, true, 200, 200)
#1 /var/www/html/app/Domain/Users/Services/Users.php(136): Leantime\Domain\Users\Repositories\Users->setPicture(Array, 1)
#2 /var/www/html/app/Domain/Api/Controllers/Users.php(88): Leantime\Domain\Users\Services\Users->setProfilePicture(Array, 1)
#3 /var/www/html/app/Core/Controller.php(98): Leantime\Domain\Api\Controllers\Users->post(Array)
#4 /var/www/html/app/Core/Controller.php(59): Leantime\Core\Controller->executeActions('POST', Array)
#5 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#6 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#7 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#8 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#9 /var/www/html/app/Core/Frontcontroller.php(120): Illuminate\Container\Container->make('Leantime\\Domain...')
#10 /var/www/html/app/Core/Frontcontroller.php(74): Leantime\Core\Frontcontroller::executeAction('api.users', Array)
#11 /var/www/html/app/Core/Bootloader.php(419): Leantime\Core\Frontcontroller::dispatch()
#12 /var/www/html/app/Core/Bootloader.php(165): Leantime\Core\Bootloader->handleRequest()
#13 /var/www/html/public/index.php(14): Leantime\Core\Bootloader->boot()
#14 {main}
  thrown in /var/www/html/app/Domain/Files/Repositories/Files.php on line 306

**Comment by schories** [comment]
Never mind - as I should have understood from "Failed to open stream: Permission denied" - it was a permission issue. 

I apologize once more.

Everything works fine. 👍
