### ISSUE TITLE
[BUG] Crash after upgrade to 2.4.7 from 2.4.5

### ISSUE THREAD

**Issue by gramakri** [Leantime/leantime#2066]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**
Upgrading from 2.4.5 to 2.4.7 results in a crash.

*Important*: Fresh installation of 2.4.7 works. Only upgrade from 2.4.5 results in crash.

**To Reproduce**
1. Fresh installation of 2.4.5
2. Create some test projects
3. Upgrade to 2.4.7
4. Login page does not work anymore

**Expected behavior**
Should not crash

**Leantime Version**
2.4.7

**Server**
Apache

**PHP / MySQL Version**
PHP 8.1

**Additional context**

```
[04-Nov-2023 09:34:06 America/Los_Angeles] PHP Fatal error:  Uncaught Exception: Plugin csvimport conflicts with domain in /app/code/app/Core/Template.php:194
Stack trace:
#0 /app/code/vendor/illuminate/collections/Collection.php(819): Leantime\Core\Template->Leantime\Core\{closure}()
#1 /app/code/app/Core/Template.php(197): Illuminate\Support\Collection->mapWithKeys()
#2 /app/code/vendor/illuminate/container/BoundMethod.php(36): Leantime\Core\Template->setupBlade()
#3 /app/code/vendor/illuminate/container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /app/code/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /app/code/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /app/code/vendor/illuminate/container/Container.php(661): Illuminate\Container\BoundMethod::call()
#7 /app/code/app/Core/Template.php(156): Illuminate\Container\Container->call()
#8 [internal function]: Leantime\Core\Template->__construct()
#9 /app/code/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#10 /app/code/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#11 /app/code/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#12 /app/code/vendor/illuminate/container/Container.php(1043): Illuminate\Container\Container->make()
#13 /app/code/vendor/illuminate/container/Container.php(959): Illuminate\Container\Container->resolveClass()
#14 /app/code/vendor/illuminate/container/Container.php(920): Illuminate\Container\Container->resolveDependencies()
#15 /app/code/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#16 /app/code/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#17 /app/code/app/Core/Frontcontroller.php(120): Illuminate\Container\Container->make()
#18 /app/code/app/Core/Frontcontroller.php(74): Leantime\Core\Frontcontroller::executeAction()
#19 /app/code/app/Core/Bootloader.php(368): Leantime\Core\Frontcontroller::dispatch()
#20 /app/code/app/Core/Bootloader.php(165): Leantime\Core\Bootloader->handleRequest()
#21 /app/code/public/index.php(14): Leantime\Core\Bootloader->boot()
#22 {main}
  thrown in /app/code/app/Core/Template.php on line 194
```

**Comment by gramakri** [comment]
I am the maintainer of the Leantime package for Cloudron. I was trying to update leantime to latest release 2.4.7. Note that there was no 2.4.6, so I attempted to update directly to 2.4.7. Let me know if you need any more information but it looks like some issue with the beta plugin which was released in 2.4.7.

**Comment by marcelfolaron** [comment]
Remove the csvImport plugin folder from plugins. 

If you are running automated updates/deployments I highly recommend to clear folders first. There are files that get moved/removed and if you just overwrite files you might get into situations like this one.

**Comment by gramakri** [comment]
Ah, I see now. I have fixed the package accordingly with your suggestion. Thanks @marcelfolaron
