### ISSUE TITLE
[BUG] Leantime broken after container update

### ISSUE THREAD

**Issue by ybizeul** [Leantime/leantime#2099]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [+] Self Hosted

**Describe the bug**
I decided to restart container that was deployed through helm chart
The welcome screen invites me to update database, which it doesn't seem to be doing, staying on that same message

![image](https://github.com/Leantime/leantime/assets/182035/0edf4dfb-6e6d-465a-b9ae-039f24977826)

I was coming from 2.4.5 it seems

There is nothing in the logs when I hit Update.

`db_version` in database is `2.4.5`

**Comment by ybizeul** [comment]
Might be related to #2008 

There is a `error.log` that is not updated when I click on update in the web ui, but shows the following errors :
```
[17-Nov-2023 22:28:19 Europe/Paris] PDOException: SQLSTATE[HY000] [2002] Operation not permitted in /var/www/html/app/Core/Db.php:66
Stack trace:
#0 /var/www/html/app/Core/Db.php(66): PDO->__construct('mysql:host=lean...', 'leantime', '4QyqMXwQT5krAlT...', Array)
#1 [internal function]: Leantime\Core\Db->__construct(Object(Leantime\Core\Environment))
#2 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#3 /var/www/html/vendor/illuminate/container/Container.php(292): Illuminate\Container\Container->build('Leantime\\Core\\D...')
#4 /var/www/html/vendor/illuminate/container/Container.php(885): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Leantime\Core\Application), Array)
#5 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build(Object(Closure))
#6 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Core\\D...', Array)
#7 /var/www/html/vendor/illuminate/container/Container.php(1043): Illuminate\Container\Container->make('Leantime\\Core\\D...')
#8 /var/www/html/vendor/illuminate/container/Container.php(959): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#9 /var/www/html/vendor/illuminate/container/Container.php(920): Illuminate\Container\Container->resolveDependencies(Array)
#10 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#11 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#12 /var/www/html/app/Core/Bootloader.php(251): Illuminate\Container\Container->make('Leantime\\Domain...')
#13 /var/www/html/app/Core/Bootloader.php(156): Leantime\Core\Bootloader->checkIfInstalled()
#14 /var/www/html/public/index.php(14): Leantime\Core\Bootloader->boot()
#15 {main}
```

**Comment by ybizeul** [comment]
I finally gained access but probably made a mess.
Ran two updates manually from the queries in https://github.com/Leantime/leantime/blob/e525aed899b94936f3e4765b1c369b8bbfaae497/app/Core/AppSettings.php#L13

Then updated `db-version` to `2.1.22`

Before realizing the container seems to be outdated :
```
    public string $appVersion = "2.4.4";

    public string $dbVersion = "2.1.22";
```

Oh well... It seems to be working for now, I'll report if there is anything broken.
