### ISSUE TITLE
News.php call to undefined function simplexml_load_file()

### ISSUE THREAD

**Issue by t-0-m-1-3** [Leantime/leantime#2247]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Updating with the current release shows a 500 error on every page; Logs output file is below
![image](https://github.com/Leantime/leantime/assets/20537914/449cc0c0-558f-4d7a-ba87-f64792a52903)

```
[26-Jan-2024 11:45:53 America/New_York] Error: Call to undefined function Leantime\Domain\Notifications\Services\simplexml_load_file() in /var/www/leantime/app/Domai
n/Notifications/Services/News.php:84
Stack trace:
#0 /var/www/leantime/app/Domain/Notifications/Services/News.php(64): Leantime\Domain\Notifications\Services\News->getFeed()
#1 /var/www/leantime/app/Domain/Notifications/Hxcontrollers/NewsBadge.php(46): Leantime\Domain\Notifications\Services\News->hasNews()
#2 /var/www/leantime/app/Core/HtmxController.php(81): Leantime\Domain\Notifications\Hxcontrollers\NewsBadge->get()
#3 /var/www/leantime/app/Core/HtmxController.php(49): Leantime\Core\HtmxController->executeActions()
#4 [internal function]: Leantime\Core\HtmxController->__construct()
#5 /var/www/leantime/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#6 /var/www/leantime/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#7 /var/www/leantime/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#8 /var/www/leantime/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make()
#9 /var/www/leantime/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction()
#10 /var/www/leantime/app/Core/HttpKernel.php(62): Leantime\Core\Frontcontroller::dispatch()
#11 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#12 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/leantime/app/Core/HttpKernel.php(62): Illuminate\Pipeline\Pipeline->then()
#14 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#15 /var/www/leantime/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle()
#17 /var/www/leantime/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle()
#19 /var/www/leantime/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle()
#21 /var/www/leantime/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle()
#23 /var/www/leantime/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle()
#25 /var/www/leantime/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle()
#27 /var/www/leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/leantime/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then()
#29 /var/www/leantime/app/Core/Bootloader.php(300): Leantime\Core\HttpKernel->handle()
#30 /var/www/leantime/app/Core/Bootloader.php(170): Leantime\Core\Bootloader->handleRequest()
#31 /var/www/leantime/public/index.php(18): Leantime\Core\Bootloader->boot()
#32 {main}
```
**To Reproduce**
1. Start a fresh installation of the newest release
2. migrate old data into new instance
3. Log into the new instance
4. See error 500 on every page, cat logs/error.log to see the above News.php error

**Expected behavior**
No 500 error

**Leantime Version**
v3.0.2

**Server**
Apache

**PHP / MySQL Version**
```bash
test@leantime-uat .../www/leantime# php --version
PHP 8.1.27 (cli) (built: Dec 21 2023 20:17:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
test@leantime-uat .../www/leantime# mysql --version
mysql  Ver 15.1 Distrib 10.5.21-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
test@leantime-uat .../www/leantime# 
```

**Additional context**
commenting out the loadXML function removed the error

![image](https://github.com/Leantime/leantime/assets/20537914/ea965ceb-1b31-420d-9450-e72e60d1eeba)

**Comment by marcelfolaron** [comment]
Fixed in 3.0.3
