### ISSUE TITLE
[BUG] Invalid dates breaking dashboard calendar

### ISSUE THREAD

**Issue by willcodetech** [Leantime/leantime#2449]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [ X] Self Hosted

**Describe the bug**
Calendar on the dashboard does not work correctly.
I updated from version 3.0.2 to 3.1 beta and errors started to appear.
Looking at the error log, it is due to invalid dates in the zp_tickets table with values 0000-00-00 00:00:00

I did some tests changing the values to null but the error also persists.

There seems to be some new validation that wasn't done before.

**To Reproduce**
1. Go to Dashboard
2. See error

**Expected behavior**
Show dates on the calendar correctly

**Leantime Version**
 v3.1.0-beta

**Server**
cPanel with nGinx

**PHP / MySQL Version**
MySQL 8.0.33-cll-lve
PHP 8.1

**Additional context**
![image](https://github.com/Leantime/leantime/assets/48792160/372c5594-894f-4914-baa4-13a0dd293fb2)

Error log:

#32 {main}
[01-Apr-2024 15:45:56 America/Sao_Paulo] Adding Event Listener to request_terminated
[01-Apr-2024 15:46:43 America/Sao_Paulo] Adding Event Listener to request_terminated
[01-Apr-2024 15:46:44 America/Sao_Paulo] Carbon\Exceptions\InvalidDateException: The string is not a valid date time string to parse as Database string : 0000-00-00 00:00:00 is not a valid value. in /leantime/app/Core/Support/DateTimeHelper.php:112
Stack trace:
#0 /leantime/app/Domain/Calendar/Repositories/Calendar.php(234): Leantime\Core\Support\DateTimeHelper->parseDbDateTime()
#1 /leantime/app/Domain/Widgets/Hxcontrollers/Calendar.php(60): Leantime\Domain\Calendar\Repositories\Calendar->getCalendar()
#2 /leantime/app/Core/HtmxController.php(81): Leantime\Domain\Widgets\Hxcontrollers\Calendar->get()
#3 /leantime/app/Core/HtmxController.php(49): Leantime\Core\HtmxController->executeActions()
#4 [internal function]: Leantime\Core\HtmxController->__construct()
#5 /leantime/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs()
#6 /leantime/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build()
#7 /leantime/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve()
#8 /leantime/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make()
#9 /leantime/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction()
#10 /leantime/app/Core/HttpKernel.php(63): Leantime\Core\Frontcontroller::dispatch()
#11 /leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#12 /leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /leantime/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then()
#14 /leantime/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}()
#15 /leantime/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle()
#17 /leantime/app/Core/Middleware/Localization.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle()
#19 /leantime/app/Core/Middleware/Auth.php(88): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle()
#21 /leantime/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle()
#23 /leantime/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle()
#25 /leantime/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /leantime/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle()
#27 /leantime/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /leantime/app/Core/HttpKernel.php(64): Illuminate\Pipeline\Pipeline->then()
#29 /leantime/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle()
#30 /leantime/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#31 /leantime/public/index.php(18): Leantime\Core\Bootloader->boot()

**Comment by willcodetech** [comment]
@marcelfolaron 
Hello!
I updated to version 3.1.1 and it seems to be working correctly.
