### ISSUE TITLE
[BUG] ErrorException: Warning: Undefined variable $canvasName in /var/www/html/app/Domain/Ideas/Templates/ideaDialog.tpl.php:144

### ISSUE THREAD

**Issue by afdhal395** [Leantime/leantime#2566]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
There will be error 500 after selecting existing milestone to the Idea entry.

**To Reproduce**
1. Create a new Idea
2. Click on Save.
3. Click on Link Existing Milestone, a drop down will appeared.
4. Select one of the Existing Milestone, then click on Save.

**Expected behavior**
No error will appear.

**Leantime Version**
3.1.4 using Docker

**Server**
Traefik Reverse Proxy

**PHP / MySQL Version**
Version that comes with Docker Image Version 3.1.4

**Additional context**
Error logs in logs/error.log

```
ErrorException: Warning: Undefined variable $canvasName in /var/www/html/app/Domain/Ideas/Templates/ideaDialog.tpl.php:144
Stack trace:
#0 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require('/var/www/html/a...')
#1 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(38): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/a...', Array)
#4 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\PhpEngine->get('/var/www/html/a...', Array)
#5 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#6 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#7 /var/www/html/cache/views/3dc53a87857b79f405bef235b27c3eaeba003bd7.php(2): Illuminate\View\View->render()
#8 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(109): require('/var/www/html/c...')
#9 /var/www/html/vendor/illuminate/filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#10 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#11 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#12 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#13 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#14 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#15 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#16 /var/www/html/app/Core/Template.php(570): Leantime\Core\Template->display('ideas.ideaDialo...', 'global::layouts...', 200)
#17 /var/www/html/app/Domain/Ideas/Controllers/IdeaDialog.php(95): Leantime\Core\Template->displayPartial('ideas.ideaDialo...')
#18 /var/www/html/app/Core/Controller.php(82): Leantime\Domain\Ideas\Controllers\IdeaDialog->get(Array)
#19 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#20 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#21 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#22 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#23 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#24 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#25 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('ideas.ideaDialo...', Array)
#26 /var/www/html/app/Core/HttpKernel.php(63): Leantime\Core\Frontcontroller::dispatch()
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#28 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#29 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#33 /var/www/html/app/Core/Middleware/Localization.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#34 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#35 /var/www/html/app/Core/Middleware/Auth.php(91): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#36 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#37 /var/www/html/app/Core/Middleware/RequestRateLimiter.php(93): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#38 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\RequestRateLimiter->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#39 /var/www/html/app/Core/Middleware/Updated.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#40 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#41 /var/www/html/app/Core/Middleware/Installed.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#42 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#43 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#44 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#45 /var/www/html/app/Core/Middleware/TrustProxies.php(81): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#46 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\TrustProxies->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#47 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#48 /var/www/html/app/Core/HttpKernel.php(64): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#50 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#51 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#52 {main}
```

**Comment by marcelfolaron** [comment]
this was fixed in 3.2.0
