### ISSUE TITLE
[BUG] Can't clear cache from leantime script

### ISSUE THREAD

**Issue by tech62** [Leantime/leantime#2583]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [X] Self Hosted

**Describe the bug**

**To Reproduce**
1.  run php bin/leantime cache:clear

**Expected behavior**
Clear the cache and return a message "successfully"

**Leantime Version**
3.2.0-beta-2

**Server**
Apache

**PHP / MySQL Version**
PHP-fpm 8.2 & Mysql (last version)

**Additional context**
```
Error: Call to undefined method Leantime\Core\Application::runningUnitTests() in /var/www/leantime/vendor/illuminate/console/Concerns/ConfiguresPrompts.php:31
Stack trace:
#0 /var/www/leantime/vendor/illuminate/console/Command.php(177): Illuminate\Console\Command->configurePrompts()
#1 /var/www/leantime/vendor/symfony/console/Application.php(1078): Illuminate\Console\Command->run()
#2 /var/www/leantime/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/leantime/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#4 /var/www/leantime/app/Core/ConsoleKernel.php(222): Symfony\Component\Console\Application->run()
#5 /var/www/leantime/app/Core/Bootloader.php(168): Leantime\Core\ConsoleKernel->handle()
#6 /var/www/leantime/app/Core/Bootloader.php(139): Leantime\Core\Bootloader->handleRequest()
#7 /var/www/leantime/bin/leantime(14): Leantime\Core\Bootloader->boot()
#8 {main}

```

**Comment by marcelfolaron** [comment]
Fixed as of 3.2.0
