### ISSUE TITLE
[BUG] Error 500 at post of login credentials version 2.1.3 and up

### ISSUE THREAD

**Issue by ArjenR** [Leantime/leantime#283]
**Describe the bug**
After the update of my docker container from version 2.1.2 to 2.1.4 I get an error 500 at the POST of the login credentials.
A downgrade to 2.1.3 does not resolve the issue, reverting to the docker image 2.1.2 does resolve it.

**To Reproduce**
1. Install docker image 2.1.0 using docker-compose
use traefik to expose it with tls
Login and setup projects, work with the projects.
2. Upgrade to docker image 2.1.2
Login, all works
3. Upgrade to docker image 2.1.4
500 error with login / blank screen 

**Expected behavior**
Login and have a working application

**Leantime Version**
2.1.3 and 2.1.4
**Server**
As provided by  official docker container.

**PHP / MySQL Version**
As provided by  official docker container.

**Additional context**
Request headers:
```
Host: myhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: nl,en-US;q=0.8,en-GB;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 107
Origin: https://pm.runsink.nl
DNT: 1
Connection: keep-alive
Referer: https://myhostl/
Cookie: sid=cookiesid
Upgrade-Insecure-Requests: 1
TE: Trailers
```

response:
```
HTTP/2 500 Internal Server Error
cache-control: no-store, no-cache, must-revalidate
content-type: text/html; charset=UTF-8
date: Wed, 27 May 2020 08:33:57 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: Apache/2.4.43 (Unix)
set-cookie: sid=cookiesid; path=/; HttpOnly
set-cookie: sid=cookiesid; expires=Wed, 27-May-2020 16:33:57 GMT; Max-Age=28800; path=/
x-powered-by: PHP/7.2.31
content-length: 0
X-Firefox-Spdy: h2
```
When I change the header `Content-Type: application/x-www-form-urlencoded` to `Content-Type: application/json` using firefox developer tools there is no 500 error.

**Comment by marcelfolaron** [comment]
Thanks for reporting. Can you check the error log in
resources/logs/error.log for any fatal errors?

**Comment by ArjenR** [comment]
I siwitched  back to latest and  recreated the issue.

This was in the log
```
[27-May-2020 10:08:13 America/Los_Angeles] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pwResetCount' in 'fi
eld list' in /var/www/html/src/core/class.login.php:566
Stack trace:
#0 /var/www/html/src/core/class.login.php(566): PDOStatement->execute()
#1 /var/www/html/src/core/class.login.php(442): leantime\core\login->getUser('xxx@xxxxx.n...')
#2 /var/www/html/src/core/class.login.php(262): leantime\core\login->getUserByLogin('xxx@xxxx.n...', '9#Q[f^,tQ`kR_u[...')
#3 /var/www/html/src/core/class.login.php(173): leantime\core\login->login()
#4 /var/www/html/src/core/class.login.php(246): leantime\core\login->__construct('dfde93ee6f1c26c...')
#5 /var/www/html/public/index.php(20): leantime\core\login::getInstance('dfde93ee6f1c26c...')
#6 {main}
  thrown in /var/www/html/src/core/class.login.php on line 566
```

**Comment by marcelfolaron** [comment]
Oh. Did the system not send you to /update to update the database?

**Comment by ArjenR** [comment]
No I did not get that. I have been looking here in the issues, the forum and the manual for that info. Perhaps I was not looking very good...

But going manually to /update did the trick. Thanks!

**Comment by marcelfolaron** [comment]
I have a suspicion. Did you mount the config folder? The DB version is
stored in config/class.settings.php

I realize that we need to move that file so it doesn't get mounted (or move
the version definition)

Can you replace that file with the current one in
https://github.com/Leantime/leantime/blob/master/config/settings.php

**Comment by ArjenR** [comment]
Yes I did. I did try to adjust configuration.php due to not getting leantime to work nicely behind traefik.  But I think in that time span 2.1.1 or 2.1.2 was released and it worked without trying to change it. 

I could just re-install the image without mounting the config?

**Comment by ArjenR** [comment]
FYI it was enough to comment out the line in my docker-compose.yaml  and redeploy.
