### ISSUE TITLE
[Bug]: reports page error 500

### ISSUE THREAD

**Issue by Double-Click-ERP** [Leantime/leantime#2830]
### What is your set up?

Self Hosted Server

### Version

3.3.2

### Describe the issue

reports page error 500

### Reproduction steps

1.open any project 
2.open reports page
3. error 500

after update from 3.3.0 (or 3.3.1 does not remember)

**Comment by marcelfolaron** [comment]
Can you share the logs in storage/logs/error.log ?

**Comment by Double-Click-ERP** [comment]
there is not error.log

leantime-2024-11-28.log
> [2024-11-28 09:10:45] production.ERROR: The string is not a valid date time string to parse as Database string : 0000-00-00 00:00:00 is not a valid value. {"exception":"[object] (Carbon\\Exceptions\\InvalidDateException(code: 0): The string is not a valid date time string to parse as Database string : 0000-00-00 00:00:00 is not a valid value. at /var/www/html/leantime/app/Core/Support/DateTimeHelper.php:120)
[stacktrace]
#0 /var/www/html/leantime/app/Domain/Sprints/Services/Sprints.php(214): Leantime\\Core\\Support\\DateTimeHelper->parseDbDateTime()
#1 /var/www/html/leantime/app/Domain/Reports/Controllers/Show.php(94): Leantime\\Domain\\Sprints\\Services\\Sprints->getSprintBurndown()
#2 /var/www/html/leantime/app/Core/Controller/Controller.php(73): Leantime\\Domain\\Reports\\Controllers\\Show->get()
#3 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(184): Leantime\\Core\\Controller\\Controller->callAction()
#4 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(83): Leantime\\Core\\Controller\\Frontcontroller->executeAction()
#5 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(91): Leantime\\Core\\Controller\\Frontcontroller->dispatch()
#6 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Leantime\\Core\\Controller\\Frontcontroller::dispatch_request()
#7 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#8 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Illuminate\\Pipeline\\Pipeline->then()
#10 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#11 /var/www/html/leantime/app/Core/Middleware/LoadPlugins.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\LoadPlugins->handle()
#13 /var/www/html/leantime/app/Core/Middleware/Localization.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Localization->handle()
#15 /var/www/html/leantime/app/Core/Middleware/SetCacheHeaders.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\SetCacheHeaders->handle()
#17 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#20 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#23 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#25 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#27 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\RequestRateLimiter->handle()
#29 /var/www/html/leantime/app/Core/Middleware/CurrentProject.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\CurrentProject->handle()
#31 /var/www/html/leantime/app/Core/Middleware/AuthCheck.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\AuthCheck->handle()
#33 /var/www/html/leantime/app/Core/Middleware/Updated.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Updated->handle()
#35 /var/www/html/leantime/app/Core/Middleware/Installed.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Installed->handle()
#37 /var/www/html/leantime/app/Core/Middleware/StartSession.php(128): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/leantime/app/Core/Middleware/StartSession.php(95): Leantime\\Core\\Middleware\\StartSession->handleStatefulRequest()
#39 /var/www/html/leantime/app/Core/Middleware/StartSession.php(64): Leantime\\Core\\Middleware\\StartSession->handleRequestWhileBlocking()
#40 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\StartSession->handle()
#41 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\InitialHeaders->handle()
#43 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\TrustProxies->handle()
#45 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/leantime/app/Core/Http/HttpKernel.php(119): Illuminate\\Pipeline\\Pipeline->then()
#47 /var/www/html/leantime/app/Core/Http/HttpKernel.php(141): Leantime\\Core\\Http\\HttpKernel->sendRequestThroughRouter()
#48 /var/www/html/leantime/app/Core/Bootloader.php(87): Leantime\\Core\\Http\\HttpKernel->handle()
#49 /var/www/html/leantime/app/Core/Bootloader.php(68): Leantime\\Core\\Bootloader->handleRequest()
#50 /var/www/html/leantime/public/index.php(14): Leantime\\Core\\Bootloader->boot()
#51 {main}
"} 
[2024-11-28 09:17:31] production.ERROR: cURL error 28: Resolving timed out after 20008 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://leantime.io/category/leantime-updates/feature-updates/feed/ {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 28: Resolving timed out after 20008 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://leantime.io/category/leantime-updates/feature-updates/feed/ at /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:275)
[stacktrace]
#0 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(205): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(157): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\\HandlerStack->__invoke()
#11 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\\Client->transfer()
#12 /var/www/html/leantime/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\\Client->requestAsync()
#13 /var/www/html/leantime/app/Domain/Notifications/Services/News.php(94): GuzzleHttp\\Client->request()
#14 /var/www/html/leantime/app/Domain/Notifications/Services/News.php(63): Leantime\\Domain\\Notifications\\Services\\News->getFeed()
#15 /var/www/html/leantime/app/Domain/Notifications/Hxcontrollers/NewsBadge.php(38): Leantime\\Domain\\Notifications\\Services\\News->hasNews()
#16 /var/www/html/leantime/app/Core/Controller/HtmxController.php(103): Leantime\\Domain\\Notifications\\Hxcontrollers\\NewsBadge->get()
#17 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(184): Leantime\\Core\\Controller\\HtmxController->callAction()
#18 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(83): Leantime\\Core\\Controller\\Frontcontroller->executeAction()
#19 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(91): Leantime\\Core\\Controller\\Frontcontroller->dispatch()
#20 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Leantime\\Core\\Controller\\Frontcontroller::dispatch_request()
#21 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#22 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Illuminate\\Pipeline\\Pipeline->then()
#24 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#25 /var/www/html/leantime/app/Core/Middleware/LoadPlugins.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\LoadPlugins->handle()
#27 /var/www/html/leantime/app/Core/Middleware/Localization.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Localization->handle()
#29 /var/www/html/leantime/app/Core/Middleware/SetCacheHeaders.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\SetCacheHeaders->handle()
#31 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#34 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#37 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#39 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#41 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\RequestRateLimiter->handle()
#43 /var/www/html/leantime/app/Core/Middleware/CurrentProject.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\CurrentProject->handle()
#45 /var/www/html/leantime/app/Core/Middleware/AuthCheck.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\AuthCheck->handle()
#47 /var/www/html/leantime/app/Core/Middleware/Updated.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Updated->handle()
#49 /var/www/html/leantime/app/Core/Middleware/Installed.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Installed->handle()
#51 /var/www/html/leantime/app/Core/Middleware/StartSession.php(128): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/leantime/app/Core/Middleware/StartSession.php(95): Leantime\\Core\\Middleware\\StartSession->handleStatefulRequest()
#53 /var/www/html/leantime/app/Core/Middleware/StartSession.php(64): Leantime\\Core\\Middleware\\StartSession->handleRequestWhileBlocking()
#54 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\StartSession->handle()
#55 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\InitialHeaders->handle()
#57 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\TrustProxies->handle()
#59 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/leantime/app/Core/Http/HttpKernel.php(119): Illuminate\\Pipeline\\Pipeline->then()
#61 /var/www/html/leantime/app/Core/Http/HttpKernel.php(141): Leantime\\Core\\Http\\HttpKernel->sendRequestThroughRouter()
#62 /var/www/html/leantime/app/Core/Bootloader.php(87): Leantime\\Core\\Http\\HttpKernel->handle()
#63 /var/www/html/leantime/app/Core/Bootloader.php(68): Leantime\\Core\\Bootloader->handleRequest()
#64 /var/www/html/leantime/public/index.php(14): Leantime\\Core\\Bootloader->boot()
#65 {main}
"}

**Comment by tech62** [comment]
Same problem for me.
And this :
![image](https://github.com/user-attachments/assets/53a4787b-a8c2-4748-ab93-bd2e869a2d25)

**Comment by marcelfolaron** [comment]
@Double-Click-ERP Thank you that helped. Seems one or more of your sprints don't have a date attached? I need to add some verification but as a quick fix you should check if all of your sprints have start and end dates.

@tech62 Can you clear your local view cache? 
Either via Leantime CLI: `php bin/leantime view:clear` or by just removing all files inside of storage/framework/views
