### ISSUE TITLE
Upgrade isssue 2.0 -> 2.1

### ISSUE THREAD

**Issue by quangbahoa** [Leantime/leantime#345]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
Upadate errors:
```
Notice: Undefined index: twoFAEnabled in /home/cowebpms/webapps/app-cowebpms/src/core/class.login.php on line 689

Notice: Undefined index: twoFAEnabled in /home/cowebpms/webapps/app-cowebpms/src/core/class.application.php on line 83

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twoFAEnabled' in 'field list' in /home/cowebpms/webapps/app-cowebpms/src/domain/users/repositories/class.users.php:188 Stack trace: #0 /home/cowebpms/webapps/app-cowebpms/src/domain/users/repositories/class.users.php(188): PDOStatement->execute() #1 /home/cowebpms/webapps/app-cowebpms/src/domain/users/services/class.users.php(33): leantime\domain\repositories\users->getAll() #2 /home/cowebpms/webapps/app-cowebpms/src/domain/dashboard/controllers/class.show.php(45): leantime\domain\services\users->getAll() #3 /home/cowebpms/webapps/app-cowebpms/src/core/class.frontcontroller.php(164): leantime\domain\controllers\show->get() #4 /home/cowebpms/webapps/app-cowebpms/src/core/class.frontcontroller.php(107): leantime\core\frontcontroller->executeAction() #5 /home/cowebpms/webapps/app-cowebpms/src/core/class.application.php(91): leantime\core\frontcontroller->run() #6 /home/cowebpms/webapps/app-cowebpms/public/index.php(41): leantime\core\ in /home/cowebpms/webapps/app-cowebpms/src/domain/users/repositories/class.users.php on line 188
```

**To Reproduce**
- Update from 2.0 to 2.1

**Expected behavior**

**Leantime Version**
2.0.4

**Server**
Nginx PHP 7.4

**PHP / MySQL Version**
MariaDB 10.2

**Additional context**

**Comment by marcelfolaron** [comment]
Is this still an issue?

**Comment by quangbahoa** [comment]
> Is this still an issue?

I'm resolve by myself. Thanks
