### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TonyBarganski** [Leantime/leantime#401]
**Description**
/var/www/html/leantime/public/css/main.css" failed (2: No such file or directory)
/var/www/html/leantime/public/js/compiled-base-libs.min.js" failed (2: No such file or directory)

main.css` & Javascript files are actually missing in the `git clone` tag: v2.0.15, origin/stable.

**Comment by Origus-Fabricio** [comment]
alguma solução?

**Comment by globule** [comment]
UBUNTU 20.04
`apt install node-grunt-cli`
... no error
```
# grunt Build-All
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'liftoff'
Require stack:
- /usr/share/nodejs/grunt-cli/bin/grunt
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/share/nodejs/grunt-cli/bin/grunt:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/nodejs/grunt-cli/bin/grunt' ]
}

```

**Comment by globule** [comment]
Grunt issue !

#cd /usr/share/nodejs/grunt-cli
#sudo sudo npm i
# npm audit fix --force

**Comment by manicmarvin** [comment]
I have used the latest leantime release ([Leantime v3.4.11](https://github.com/Leantime/leantime/releases/tag/v3.4.11)) and am facing the same issue.

**Comment by marcelfolaron** [comment]
Did you use the release build or just the source code? You need to use the release build to get the compiled css and js resources, otherwise you need to run all the build commands.
