### ISSUE TITLE
[BUG] HTTP 500 with various 

### ISSUE THREAD

**Issue by aarchijs** [Leantime/leantime#417]
**Describe the bug**
Multiple HTTP 500 responses
- On Login initial response from Apache is 500 after refresh page loads to project to-do dashboard.

- When changing project in [My Portfolio>Open Project button] results in HTTP 500. Reload does not work. When I delete this "dashboard/show?projectId=5" from URL then I see selected project to-do dashboard. 

- When I create new project [All projects>New project>Name new project>Save] then I get HTTP 500. Reloading page will make multiple copies of the same project name. When I delete this from URL "projects/newProject/" then I get to newly created project to-do dashboard.

**Expected behavior**
Directed to new page or something without additional manual URL edits or page refresh.

**Leantime Version**
V2.1.7

**Server**
Tested both Apache and Nginx

**PHP / MySQL Version**
PHP 7.4 / Mysql 8 and MariaDB 10.3

**Additional context**
All tested browsers has the same result Chromium based and Firefox.

It is unclear why page is not loading or redirecting correctly.

**Comment by kevev** [comment]
Same error here. Is there a fix?

**Comment by kevev** [comment]
error.log

`06-May-2021 14:59:55 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to undefined function leantime\domain\services\mb_strlen() in /var/www/Leantime/src/domain/projects/services/class.projects.php:390
Stack trace:
#0 /var/www/Leantime/src/domain/projects/services/class.projects.php(342): leantime\domain\services\projects->changeCurrentSessionProject()
#1 /var/www/Leantime/src/core/class.application.php(88): leantime\domain\services\projects->setCurrentProject()
#2 /var/www/Leantime/public/index.php(41): leantime\core\application->start()
#3 {main}
  thrown in /var/www/Leantime/src/domain/projects/services/class.projects.php on line 390`

**Comment by kevev** [comment]
Fixed!

Ubuntu 20.04

`apt-get install php7.4-mbstring`

`systemctl restart apache2`

**Comment by mitchellurgero** [comment]
After investigating more into the logs - I ended up needing to configure the smtp stuff with some data to be able to resolve my end of the issue.
